---
- hosts: internet
  tasks:
   - name: Configure switch to act as campus/internet
     nclu:
       commands:

         - add loopback lo ip address 192.168.150.1/32
         - add interface swp1 ip address 172.16.2.1/30
         - add interface swp2 ip address 172.16.2.5/30
         - add ospf network 192.168.150.1/32 area 0.0.0.0
         - add ospf network 172.16.2.0/24 area 0.0.0.0

       commit: true

- hosts: 3850-1
  tasks:
   - name: Configure 3850-1
     nclu:
       commands:

         - add loopback lo ip address 192.168.150.2/32
         - add interface swp49 ip address 172.16.2.2/30
         - add vlan 100 ip address 172.16.1.2/24
         - add vlan 100 ip address-virtual 00:00:5e:00:a0:01 172.16.1.1/24
         - add bond peerlink bond slaves swp51-52
         - add interface peerlink.4094 clag peer-ip linklocal
         - add interface peerlink.4094 clag backup-ip 192.168.150.3
         - add interface peerlink.4094 clag sys-mac 44:38:39:FF:01:01
         - add interface peerlink.4094 clag priority 100
         - add bridge bridge ports peerlink
         - add bridge stp treeprio 8192
         - add ospf network 172.16.0.0/16 area 0.0.0.0
         - add ospf network 192.168.150.2/32 area 0.0.0.0

       commit: true

- hosts: 3850-2
  tasks:
   - name: Configure 3850-2
     nclu:
       commands:

         - add loopback lo ip address 10.19.241.3/32
         - add interface swp49 ip address 172.16.2.6/30
         - add vlan 100 ip address 172.16.1.3/24
         - add vlan 100 ip address-virtual 00:00:5e:00:a0:01 172.16.1.1/24
         - add bond peerlink bond slaves swp51-52
         - add interface peerlink.4094 clag peer-ip linklocal
         - add interface peerlink.4094 clag backup-ip 192.168.150.2
         - add interface peerlink.4094 clag sys-mac 44:38:39:FF:01:01
         - add bridge bridge ports peerlink
         - add bridge stp treeprio 8192
         - add ospf network 172.16.0.0/16 area 0.0.0.0
         - add ospf network 192.168.150.3/32 area 0.0.0.0

       commit: true


- hosts: 3048-1
  tasks:
   - name: Configure 3048-1
     nclu:
       commands:

         - add bond bond01 bond slaves swp49-50
         - add bond bond01 bridge trunk vlans 100
         - add vlan 100
         - add interface swp1 bridge access 100

       commit: true

- hosts: 3048-2
  tasks:
   - name: Configure 3048-2
     nclu:
       commands:

         - add bond bond01 bond slaves swp49-50
         - add bond bond01 bridge trunk vlans 100
         - add vlan 100
         - add interface swp1 bridge access 100

       commit: true

- name: Configure Server LACP Interfaces
  hosts: servers
  become: yes
  gather_facts: yes
  tasks:

  - name: Copy Server LACP Interface Config
    copy:
      src: configurations/{{ansible_hostname}}/interfaces
      dest: /etc/network/interfaces
    register: reboot

  - name: reboot
    reboot:
      pre_reboot_delay: 60
